name: hello-world

on: workflow_dispatch:
  inputs:
    description: 'Purge Date'
    required: true
    type: choice
    options:
    - A
    - B

# on: workflow_dispatch:
#   inputs:
#     purgeDate:
#       description: 'Date to purge records from'
#       required: true
#       type: string

#on: push

jobs:
  hello-world-job:
  
    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
